version: "3"
services:
  app:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_USER:
      DATABASE_PASSWORD:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: polls
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      TZ: "Asia/Tokyo"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
